alter table documents
  add column if not exists source_id bigint generated by default as identity;

create unique index if not exists documents_source_id_uidx on documents(source_id);

alter table chat_citations
  add column if not exists source_id bigint;

update chat_citations citation
set source_id = document.source_id
from chunks chunk
join documents document on document.id = chunk.document_id
where citation.chunk_id = chunk.id
  and citation.source_id is null;
